### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by vmorenomarin** [naraesk/krunner-translator#1]
When begin the compilation process appears this error:

```
Could not find a package configuration file provided by "ECM" (requested
  version 5.12.0) with any of the following names:

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.

  -- Configuring incomplete, errors occurred!

```
Running under:

![image](https://cloud.githubusercontent.com/assets/13444664/22487278/c58d1330-e7da-11e6-937c-f95deaab7b52.png)

Any suggestion? Thanks.

**Comment by naraesk** [comment]
Please try to install the package extra-cmake-modules and try again.

**Comment by vmorenomarin** [comment]
Thanks a lot. Works very well. Congratulations!!

Why not is official as a default feature in kRunner?

**Comment by naraesk** [comment]
Aktually it was for KDE 4 but wasn't migrated to KDE Frameworks due to the api shutdown of Google Translate. I thought, the current need for an api key might be a bit clumsy for a default plugin.
