### ISSUE TITLE
I need some help with the dependencies

### ISSUE THREAD

**Issue by bipox** [naraesk/krunner-translator#10]
Hi,

I'm trying to install this on KDE Neon (based on Ubuntu)

I'm not really familiar with cmake, only used in a few times following a tutorial

Everytime I see an error message, I install the dependencies, but the errors keep coming.

Now I'm stuck at this point

```
cmake .. -DCMAKE_INSTALL_PREFIX=`kf5-config --prefix` -DKDE_INSTALL_QTPLUGINDIR=`kf5-config --qt-plugins`
-- Could NOT find KF5Runner (missing: KF5Runner_DIR)
-- Could NOT find KF5Runner: found neither KF5RunnerConfig.cmake nor kf5runner-config.cmake 
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find KF5 (missing: Runner) (found version "5.63.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindKF5.cmake:110 (find_package_handle_standard_args)
  CMakeLists.txt:12 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/remi/bin/krunner-translator-1.1.1/build/CMakeFiles/CMakeOutput.log".
```

Thanks

**Comment by naraesk** [comment]
Yes, dependencies are annoying. The missing package should be `libkf5runner-dev`.

**Comment by bipox** [comment]
Thank you. Yes I missed that. 

Wouldn't it be easier with a list of dependencies? (sorry if I'm saying something stupid)

So I have the program installed, I tried with Glosbe or Yandex (with api key) but nothing shows up
```
en-fr house
fr house
fr-en maison
fr maison
```
shows nothing

**Comment by naraesk** [comment]
The problem is, that the list of dependencies differs for every linux distribution. I cannot provide an uptodate list for every disto.

Please restart krunner after setting up the yandex api key, just to make sure. Glosbe had many downtimes recently. But this a problem on their side, nothing I can fix. But yandex should definetly work.

**Comment by bipox** [comment]
I didn't think to restart it. Hurray, it works!

Thank you for this addon and your help

And noted about dependencies, I'm still learning how it all works. They are annoying indeed!

**Comment by naraesk** [comment]
No problem. :) Glad it worked!
