### ISSUE TITLE
Can't compile ECM error

### ISSUE THREAD

**Issue by ErSoul** [naraesk/krunner-translator#3]
Hello, I tried to compile this addon, but without success. CMake drops the following error:

```
  CMake Error at CMakeLists.txt:4 (find_package):                                                                                                         
  Could not find a package configuration file provided by "ECM" (requested                                                                              
  version 5.12.0) with any of the following names:                                                                                                      

    ECMConfig.cmake
    ecm-config.cmake

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/erdave/AUR/krunner-translator/build/CMakeFiles/CMakeOutput.log".
```

The pointed log, doesn't contain any relevant information as I see.

**Comment by naraesk** [comment]
Hello, thanks for reporting. You were using the aur package?

**Comment by ErSoul** [comment]
Negative, I just put all my downloaded non-repos applications in that 
directory. Indeed, there's no AURs PKGBUILD.

I cloned it directly from GIT.

**Comment by naraesk** [comment]
Do you have extra-cmake-modules installed?

**Comment by ErSoul** [comment]
On domingo, 6 de mayo de 2018 4:02:02 A. M. -04 naraesk wrote:
> Do you have extra-cmake-modules installed?

I didn't. I've installed it now, and it is now running and "activated" by 
krunner. But it doesn't have any effect on krunner: can't translate. (Already 
tried restarting the application, the session, and the OS)

What I typed:

`en-es hello`

But I get nothing.

**Comment by naraesk** [comment]
Could you post a screenshot of the config dialog?

**Comment by ErSoul** [comment]
![image](https://user-images.githubusercontent.com/4327047/39710406-b8bad5ea-51ea-11e8-8f70-717949fa6af3.png)

Sure, there it is.

**Comment by naraesk** [comment]
Sorry for the delay. Just realeased version 1.1.0 which should fix the problem :-)

**Comment by evo17** [comment]
It's working now. Thank You :)
