### ISSUE TITLE
Translation not working when target language is also a source language

### ISSUE THREAD

**Issue by simgunz** [naraesk/krunner-translator#5]
Default source language: English
Alternative  source language: German

de home / Translated to home
en blau / Translate to blau

The examples you provide do not work as expected. Indeed they are not translated at all. Many other words have the same problem.

This is not always the case though.

da street / Translated to gade

Any idea why does this happen for many words?

I am using Yandex.

**Comment by naraesk** [comment]
Thangs for reporting this issue. It appears that the original word is always displayed as translation. This is a bug. However, translation still works. With your settings and "en blau" I get 3 additional results: blue, drunk, and azure

**Comment by simgunz** [comment]
With "en blau" now I get blue, but I do not get the other two results. Please see issue #6, maybe when you tested it the settings were not actually applied. I get more results if also globse is active.

In my first report I said that "da street" works, but it should be "de street" and the result is "street", which is wrong. (da is Danish, so there is no ambiguity).

**Comment by simgunz** [comment]
Yes indeed there are some translation errors. Maybe you can change the example for home in the documentation, given that it is an unlucky case, and close the issue.

**Comment by naraesk** [comment]
Done
