### ISSUE TITLE
Settings not applied until krunner is restarted

### ISSUE THREAD

**Issue by simgunz** [naraesk/krunner-translator#6]
**Steps to reproduce**
- Select Yandex "Translate phrases and sentences" and disable all other features.
- Restart krunner `pkill krunner`
- Translate a sentence `en-de How are you?` (Result: Wie sind Sie?)
- Uncheck Yandex "Translate phrases and sentences"
- Translate a sentence `en-de How are you?` 

**Expected result**
Nothing 

**Actual Result**
Wie sind Sie?

The problem is the same with the other features in the settings page.

**Comment by naraesk** [comment]
Just had a look at the other runners that are shipped with KDE by default. Every runner with configuration options requires a restart of KRunne after changing settings as far as I can tell. Or can you point me to a runner where this actually works?

**Comment by simgunz** [comment]
You are right indeed. So it seems it is a krunner bug. I'll report it upstream.

**Comment by alex1701c** [comment]
Fixed with https://invent.kde.org/frameworks/krunner/-/merge_requests/7/diffs in Plasma 5.20
