### ISSUE TITLE
How to uninstall it?

### ISSUE THREAD

**Issue by mambusskruj** [naraesk/krunner-translator#7]
Hi, I just tried such krunner module, but I want to uninstall it from system. How can I do it?

**Comment by mambusskruj** [comment]
Yeah, I noticed few things:
1. disabled/enabled Glosbe parameters doesn't really affect. It's always show word description for one word and examples for phrase. 
2. Krunner got example sentances with html tags.
3. After some time using it, seems like translator plugin just go down and don't showing any translations. Reinstalling and restart krunner doesn't help.

**Comment by naraesk** [comment]
Please note, that krunner must be restarted after changing settings, e.g. with `kquitapp5 krunner &&
krunner`. Can't notice any problems with glosbe settings.

Can you remember your languages and search term when html tags appeared? Have never seen this before, but should be easy to remove them.
