### ISSUE TITLE
Glosbe not working

### ISSUE THREAD

**Issue by alexgallotta** [naraesk/krunner-translator#8]
I installed in archlinux, set up yandex API keys and it works fine.
Although it seems glosbe is not working. I tried to remove the "translate with yandex" and select only glosbe and I get no translation

**Comment by naraesk** [comment]
Thanks for the report. Can you test with only one word to translate, e.g. translating "house" into another language, please? Does this work?

**Comment by alexgallotta** [comment]
Yes I tested it, it doesn't seem to work. If there is some way to get logs I can try to give more info

**Comment by naraesk** [comment]
Ok, turned out the problem is on glosbe site. There does not work at the moment and only returns 429 error pages. There is nothing I can do about that. Hopefully they fix their api soon.

**Comment by alexgallotta** [comment]
Ok, thanks for double checking!
