### ISSUE TITLE
Add google translate support

### ISSUE THREAD

**Issue by alexgallotta** [naraesk/krunner-translator#9]
It would be nice to add google translate support.
There is already another project for Krunner google translate here 
https://github.com/gtgt/krunner-googletranslate
if it can be of any help

**Comment by naraesk** [comment]
This project used Google Translate in the past. However, Google has closed the APIs some years ago. It is only possible to use it if you pay. Therefore I switched to Yandex and Glosbe. 

Of course it would be possible to support the fee-based API. Users have to provide their login information and have to actually pay for it. But I don't think anybody would use that.

**Comment by naraesk** [comment]
v1.3.0 now supports Google Translate again.
